server:
  port: 8080  # Spring boot Server port

spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /h2-console  # 콘솔의 경로

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:testdb
    username: sa  # 사용자 이름 (로그인 시 사용)
    password:   # 사용자 암호 (로그인 시 사용)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
    root : WARN
    org.springframework.security : DEBUG
    org.hibernate.type.descriptor.sql: DEBUG


gretting :
  welcome :${spring.application.name}


